### ISSUE TITLE
BLOCKER - Features: Incomplete or Vague

### ISSUE THREAD

**Issue by JayR-LC** [kjy/liftoff-assignments#2]
There are features that aren't represented here. For example, finding and adding friends, or sending them messages, aren't listed in the features, just in the overview. Can you view all your saved messages? 
Because the Features section is light and mostly focused on the necessary tech, it's harder for me to have a complete picture of what your application is intended to look like in its complete state. One of the goals of the Outline is to have a complete high level view of what your application does.

**Comment by kjy** [comment]
The user should be able to see all saved messages.  Friends don't have to be on the  app for the user to send them a push notification. They can send direct to their phone.  I may have search and find friends features on it.

**Comment by kjy** [comment]
Outline has been updated with feedback.
