### ISSUE TITLE
"Using data from a public API" 

### ISSUE THREAD

**Issue by JayR-LC** [kjy/liftoff-assignments#3]
which API will be you be using, or if you haven't chosen yet, what do you need an API
for and what are some potential options?

**Comment by kjy** [comment]
There was one source that was discusses in the last lecture class of Unit 2. It had a bunch of APIs. There was a weather one. I'll have to look for it.

**Comment by kjy** [comment]
Action taken is that outline has been updated with link that has various API websites to use for pulling weather data.
